<?php
declare(strict_types=1);

namespace SoftUni\Config;

/* Add custom routes
 * You can use regex with named groups <controller>, <action>, <params>
 * to create specific routing
 *  * Example:
 * To match the creation of a new product/user/promotion, you can add this route
 *
 *  '/^new\/(?<controller>.*?)\/(?<action>.*?)\/(?<params>.*)$/i'
 *
 * matched uri will be:
 *    "newProduct/Create/Cake/With3Eggs"
 *    "newUser/CreateProfile/FromFacebook"
 *
 * *
 * You can also use a special syntax to add custom route. The route regex will be generated by the framework
 * <controller:{string}>/<action:{int}>/<id:{int}>
 *
 */

class RouteConfig
{
    const CustomRouteConfigs = array(
        '<controller:{string}>/<action:{string}>/<id:{int}>',
        '#^\/users\/(?<controller>[^\/\\\]+?)\/(?<action>[^\/\\\]+?)\/(?<params>[^/\\\]+?)$#i',
        '#^\/users\/(?<controller>[^\/\\\]+?)\/(?<action>[^\/\\\]+?)$#i'
    );

    const DefaultFrameworkRouteConfigs = array(
        '#^\/(?<controller>[^\/\\\]+?)\/(?<action>[^\/\\\]+?)\/(?<params>[^\/\\\]+?)$#i',
        '#^\/(?<controller>[^\/\\\]+?)\/(?<action>[^\/\\\]+?)$#i'
    );
}